spring.application.name=demo

# Config para Oracle local
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.username=system
spring.datasource.password=tu_password

# Config JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true


# esto era para pruebas
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true